import type {Metadata,Viewport} from 'next';import {Manrope} from 'next/font/google';import {Header} from '@/components/header';import {Footer} from '@/components/footer';import {siteUrl} from '@/lib/metadata';import {agency} from '@/lib/content';import {ThemeProvider} from '@/components/theme-provider';import './globals.css';
import {TravelMotionProvider} from '@/components/travel-motion-provider';
import {LaunchSwoosh} from '@/components/launch-swoosh';
import {FlightCursor} from '@/components/flight-cursor';
import './atlas.css';
const manrope=Manrope({subsets:['latin'],display:'swap',variable:'--font-manrope'});
export const metadata:Metadata={metadataBase:new URL(siteUrl),title:{default:'Prosperity Travel | Your trusted partner in every journey',template:'%s | Prosperity Travel'},description:'Discover Japan, Korea, Türkiye, Greece and Dubai. Personal travel planning, tour arrangements and documentation assistance from Prosperity in Cabuyao, Laguna.',icons:{icon:'/icon.png',apple:'/icon.png'}};
export const viewport:Viewport={width:'device-width',initialScale:1,themeColor:'#0b3734',colorScheme:'light dark'};
export default function RootLayout({children}:{children:React.ReactNode}){const schema={'@context':'https://schema.org','@type':'TravelAgency',name:agency.name,url:siteUrl,telephone:agency.phoneIntl,email:agency.email,address:{'@type':'PostalAddress',streetAddress:'#001 Rosario Village, Brgy. Sala, Stall 8 Sukimart',addressLocality:'Cabuyao',addressRegion:'Laguna',addressCountry:'PH'},sameAs:[agency.facebook],foundingDate:'2024'};return <html lang="en" suppressHydrationWarning><body className={manrope.variable}><ThemeProvider><TravelMotionProvider><LaunchSwoosh/><FlightCursor/><a href="#main-content" className="skip-link">Skip to content</a><Header/><main id="main-content">{children}</main><Footer/></TravelMotionProvider></ThemeProvider><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/></body></html>}
