'use client';
import {useCallback,useEffect,useState} from 'react';import useEmblaCarousel from 'embla-carousel-react';
import {motion,useReducedMotion} from 'motion/react';import Image from 'next/image';import Link from 'next/link';
import {IconArrowLeft,IconArrowRight,IconArrowUpRight} from '@tabler/icons-react';import {destinations} from '@/lib/content';
export function DestinationCarousel(){const [ref,api]=useEmblaCarousel({align:'start',containScroll:'trimSnaps',loop:false});const [selected,setSelected]=useState(0);const [snapCount,setSnapCount]=useState(1);const [previous,setPrevious]=useState(false);const [next,setNext]=useState(true);const reduce=useReducedMotion();
 const update=useCallback(()=>{if(!api)return;setSelected(api.selectedScrollSnap());setSnapCount(api.scrollSnapList().length);setPrevious(api.canScrollPrev());setNext(api.canScrollNext());},[api]);
 useEffect(()=>{if(!api)return;api.on('select',update).on('reInit',update);const frame=requestAnimationFrame(update);return()=>{cancelAnimationFrame(frame);api.off('select',update).off('reInit',update);};},[api,update]);
 return <section className="section destination-section" aria-labelledby="destinations-heading"><div className="container section-heading"><h2 id="destinations-heading">Where will your<br/>next story begin?</h2><p>Five places to spark your plans.<br/>One team to help you get there.</p><Link className="text-link" href="/destinations">Explore all destinations <IconArrowUpRight size={19} aria-hidden/></Link></div><div className="destination-viewport" ref={ref} role="region" aria-roledescription="carousel" aria-label="Featured destinations" tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();api?.scrollNext();}if(e.key==='ArrowLeft'){e.preventDefault();api?.scrollPrev();}}}><div className="destination-track">{destinations.map((d,i)=><article className="destination-slide" key={d.slug} aria-roledescription="slide" aria-label={`${i+1} of ${destinations.length}: ${d.name}`}><motion.div className="destination-card" animate={{scale:reduce?1:selected===i?1:.96,opacity:selected===i?1:.9}} transition={{type:'spring',stiffness:150,damping:25}}><Link href={`/destinations/${d.slug}`} className="destination-photo"><Image src={d.image} alt={d.alt} fill sizes="(max-width: 600px) 78vw, (max-width: 1024px) 43vw, 350px"/><div className="destination-caption"><h3>{d.name}</h3><span className="round-arrow"><IconArrowUpRight size={23} aria-hidden/></span></div></Link><p>{d.region}<span>{d.phrase}</span></p></motion.div></article>)}</div></div><div className="container carousel-footer"><p className="carousel-status" aria-live="polite">Explore at your pace <span>View {selected+1} / {snapCount}</span></p><div className="carousel-buttons"><button className="icon-button" aria-label="Previous destination" disabled={!previous} onClick={()=>api?.scrollPrev()}><IconArrowLeft aria-hidden/></button><button className="icon-button" aria-label="Next destination" disabled={!next} onClick={()=>api?.scrollNext()}><IconArrowRight aria-hidden/></button></div></div></section>;
}
